Add ability to view all talent information(profile) #6
Vladyslav-Team/backend pull request #40
Opened 2023-03-29 13:13 UTC by PanfiDen

Task for user story: [#2](https://github.com/Vladyslav-Team/frontend/issues/14)

Created a new method in the service and wrote the business logic to process the talent profile

Created a new endpoint @GetMapping("/talents/{talent-id}")

As a result, we get extended information about Talent in JSON format

2023-03-29 13:18 UTC, IlliaKyselov1902 approved these changes

2023-04-01 19:36 UTC, SEM24 requested changes

2023-04-01 19:36 UTC, SEM24 commented on src/main/java/com/softserve/skillscope/mapper/TalentMapper.java
> +                .age(talent.getTalentInfo().getAge())
Change field from local date to int age

2023-04-01 19:36 UTC, SEM24 commented on src/main/java/com/softserve/skillscope/talent/TalentServiceImpl.java
> +        return talentMapper.toTalentProfile(talentRepo.findById(talentId).orElseThrow(TalentNotFoundException::new));
Check if current talent deletes own account, not others.

2023-04-01 19:36 UTC, SEM24 commented on src/main/java/com/softserve/skillscope/talent/model/dto/TalentProfile.java
> +        @NotBlank LocalDate age,
int age insted local date

2023-04-01 19:36 UTC, SEM24 commented on src/main/java/com/softserve/skillscope/mapper/TalentMapper.java
Move this code from interface to class that will be added in dev branch. Delete target package before building the project to avoid crashing code

2023-04-03 10:27 UTC, merged