Add the ability to delete the talent's account
Vladyslav-Team/backend pull request #42
Opened 2023-03-31 09:38 UTC by PanfiDen

- Wrote logic in service which deletes talent, depending on given parameter from controller.
 - Write DeleteMapping() which gets request body/request param with our talent.

2023-04-01 19:38 UTC, SEM24 requested changes
Check if current talent deletes own account, not others. Else is fine

2023-04-01 19:38 UTC, SEM24 commented on src/main/java/com/softserve/skillscope/talent/TalentServiceImpl.java
> +    public DeletedTalent delete(Long talentId){
Check if current talent deletes own account, not others.

2023-04-01 19:38 UTC, SEM24 commented on src/main/java/com/softserve/skillscope/talent/TalentServiceImpl.java
> +        var talent = talentRepo.findById(talentId)
Use Talent insted var. Bad practice

2023-04-02 10:32 UTC, IlliaKyselov1902 commented on src/main/java/com/softserve/skillscope/talent/TalentServiceImpl.java
> +        var talent = talentRepo.findById(talentId)
I am agree with Samer

2023-04-03 16:40 UTC, IlliaKyselov1902 commented on src/main/resources/application.properties
pro -> prod

2023-04-03 19:20 UTC, IlliaKyselov1902 approved these changes

2023-04-04 16:01 UTC, SEM24 approved these changes

2023-04-04 16:09 UTC, merged